"""Adiciona data previsão em uma conta

Revision ID: 0b7fbaea9034
Revises: 75d2629bbb13
Create Date: 2024-05-09 14:56:36.591617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7fbaea9034'
down_revision: Union[str, None] = '75d2629bbb13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_pagar_e_receber', sa.Column('data_previsao', sa.DateTime(), nullable=True))
    op.execute("UPDATE contas_a_pagar_e_receber SET data_previsao = now() WHERE data_previsao IS NULL")
    op.alter_column('contas_a_pagar_e_receber', 'data_previsao', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas_a_pagar_e_receber', 'data_previsao')
    # ### end Alembic commands ###
