"""Adiciona colunas de controle de baixa de uma conta

Revision ID: 75d2629bbb13
Revises: 0a52c049cf16
Create Date: 2024-05-08 16:06:23.972192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d2629bbb13'
down_revision: Union[str, None] = '0a52c049cf16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
